plugins:
  - tableau_hll
  - transparent

settings:
  log-level: debug
  intercept-log: logs/intercept.log
  general-log: logs/general.log

instances:
  - listen:
      name: local_proxy
      host: 127.0.0.1
      port: 5111
    redirect:
      name: postgresql
      host: 127.0.0.1
      port: 5432
    intercept:
      commands:
        queries:
          - plugin: transparent
            function: rewrite_query
        connects:
      responses:
